-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Profiles Table
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  is_admin boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  type text check (type in ('image', 'video')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Media Assets Table
create table media_assets (
  id uuid default uuid_generate_v4() primary key,
  title text not null,
  description text,
  file_url text not null,
  format text not null,
  asset_type text check (asset_type in ('image', 'video')) not null,
  category_id bigint references categories(id),
  uploader_id uuid references profiles(id),
  is_recommended boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Storage Bucket
insert into storage.buckets (id, name, public) values ('assets', 'assets', true);

-- 5. RLS Policies

-- Profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Only admins can update is_admin (This needs a secure way to bootstrap, usually done via SQL editor or edge function, 
-- but for RLS, we check if the executing user is admin. 
-- However, to prevent circular dependency or locking yourself out, we rely on manual admin promotion in SQL editor first).

-- Categories
alter table categories enable row level security;

create policy "Categories are viewable by everyone."
  on categories for select
  using ( true );

create policy "Admins can insert categories."
  on categories for insert
  with check ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Admins can update categories."
  on categories for update
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Admins can delete categories."
  on categories for delete
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

-- Media Assets
alter table media_assets enable row level security;

create policy "Media assets are viewable by everyone."
  on media_assets for select
  using ( true );

create policy "Admins can insert media assets."
  on media_assets for insert
  with check ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Admins can update media assets."
  on media_assets for update
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Admins can delete media assets."
  on media_assets for delete
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

-- Storage Policies
-- We need to enable RLS on storage.objects
-- alter table storage.objects enable row level security;

create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'assets' );

create policy "Admin Upload"
  on storage.objects for insert
  with check ( bucket_id = 'assets' and exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Admin Delete"
  on storage.objects for delete
  using ( bucket_id = 'assets' and exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Seed Categories
insert into categories (name, type) values
('Nature', 'image'),
('Technology', 'image'),
('Abstract', 'image'),
('Nature', 'video'),
('Technology', 'video'),
('Abstract', 'video');
